### ISSUE TITLE
一键运行脚本 有错误

### ISSUE THREAD

**Issue by swflysnow** [UCoinTeams/AddU2hosts#4]
wget ${web_proxy} https://github.com/XIU2/CloudflareSpeedTest/releases/download/v2.0.3/CloudflareST_linux_amd64.tar.gz -O CloudflareST_linux_amd64.tar.gz
 这行有错
 要修改为
  wget -e http_proxy=${web_proxy} https://github.com/XIU2/CloudflareSpeedTest/releases/download/v2.0.3/CloudflareST_linux_amd64.tar.gz -O CloudflareST_linux_amd64.tar.gz 才能正常利用代理来下载

**Comment by Ukenn2112** [comment]
其实也是可以用的，用的cf的反戴，最近不能用了是因为之前那域名过期了，现已更新
