### ISSUE TITLE
main页bat脚本运行失败

### ISSUE THREAD

**Issue by KanlentB** [UCoinTeams/AddU2hosts#6]
运行了一遍旧脚本，看到有更新，然而没有发布release，从主页下代码运行失败
![image](https://user-images.githubusercontent.com/62445941/211140204-8b88d477-4ac6-48fa-864f-88171eb2a31f.png)

**Comment by Ukenn2112** [comment]
Windows脚本有编码问题，上传到GitHub再下回来就运行不了，Windows 只能用release版
